myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('user.urls','user'),namespace="user")),

]

user/urls.py
from django.urls import path
from . import views
from .views import BlogList,BlogDetail,BlogCreate,BlogDelete,BlogUpdate,LoginView,LogoutView
from django.urls import reverse_lazy 
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index,name="index"),
    path('navi',views.nav,name="nav"),
    path('blog/',BlogList.as_view(),name='blogs'),
    path('detail/<int:pk>/',BlogDetail.as_view(),name='blogdetail'),
    path('create/',BlogCreate.as_view(),name='blogcreate'),
    path('remove/<int:pk>/',BlogDelete.as_view(),name='blogdelete'),
    path('edit/<int:pk>/',BlogUpdate.as_view(),name='update'),
    path('signin/',LoginView.as_view(),name='signin'),
    path('logout/',LogoutView.as_view(next_page='user:signin'),name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    title= models.CharField(max_length=100)
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    published_on= models.DateTimeField(auto_now_add=True)
    image=models.ImageField(upload_to="media")
    description= models.TextField()
    updated_on= models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-published_on']

    def __str__(self) :
        return self.title

user/views.py
from django.shortcuts import render
from .models import Blog 
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy 
from django.contrib.auth.views import LoginView,LogoutView


# Create your views here.
class LoginView(LoginView):
    template_name='user/signin.html'
    fields='__all__'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('user:index')



def index(request):
    return render(request,'user/index.html')

def nav(request):
    return render(request,'user/navigation.html')

class BlogList(ListView):
    model = Blog
    template_name='user/blog.html'
    context_object_name='blogs' 

class BlogDetail(DetailView):
    model = Blog
    template_name='user/detail.html'
    context_object_name='blog' 

class BlogCreate(CreateView):
    model = Blog
    fields ='__all__'
    success_url = reverse_lazy('index')

class BlogUpdate(UpdateView):
    model=Blog
    fields='__all__'
    success_url = reverse_lazy('blogs')

class BlogDelete(DeleteView):
    model=Blog
    fields='__all__'
    success_url = reverse_lazy('blogs')
    context_object_name='blog' 
    template_name='user/delete.html'

user/templates/user/blog.html
{% extends  'user/navigation.html'%}
{%load static%}
{%block main_content%}
<div class="middle">
      <h1>Posts</h1>
      <h4><a href="{% url 'user:blogcreate' %}">Add Blog</a></h4>
        
    
      {% for blog in blogs %}
      <div class='blog'>
        <div class='title'>{{ blog.title}}</div>
        <div class='list'>
        <ul>
			 <a href="{% url 'user:blogdetail' blog.id %}"><li>View</li></a>
       <a href= "{% url 'user:blogdelete' blog.id %}"><li>Delete</li></a>
       <a href= "{% url 'user:update' blog.id %}"><li>Edit</li></a>
       </ul>
       </div>
       </div>
	
      {% endfor %}
  
</div>
{% endblock%}
   

user/templates/user/blog_form.html
{% extends  'user/navigation.html'%}
{%load static%}
{%block main_content%}
    <div class="form">
    <a href="{% url 'user:blogs' %}"> Back </a>
    <form method="Post" action="">
     {%csrf_token%}
    {{form.as_p}}
        <input type="submit">
    </form>
        
    </div>
{% endblock%}
   

user/templates/user/delete.html
<a href="{% url 'user:blogs' %}"> Back </a>
<form method="POST">
{%csrf_token%}
<p>Are you sure want to delete this blog?"{{blog}}"</p>
<input type="submit" value="Delete"/>
</form>

user/templates/user/detail.html
{% extends  'user/navigation.html'%}
{%load static%}
{%block main_content%}
<div class="blogsd">
    <h1 class="dtitle">{{blog.title}} </h1><br>
<img class="dimage" src="{{blog.image.url}}">
<p class="descrip">{{blog.description}}</p><br>
<p class="dauthor">By:-{{blog.author}}</p>
</div>
{%endblock%}

user/templates/user/index.html
{% extends  'user/navigation.html'%}
{%load static%}
{%block main_content%}
{%if request.user.is_authenticated%}
    {{request.user}}
    <a href=" {%url 'user:logout' %}">Logout</a>
{% else %}
    <a href="{%url 'user:signin' %}">Login</a>
{% endif %}
    <div class="mid">
        
    </div>
{% endblock%}
   

user/templates/user/navigation.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'user/css/main.css' %}">

</head>
    <body>
        <div class="navbar">
            <a  class="naviteam" href ="{%url 'user:index' %}">Home</a>
            <a class="naviteam" href ="{%url 'user:blogs' %}">Blog</a>
            <a class="naviteam" href ="{%url 'user:nav' %}">AboutUs</a>
        </div>

        {%block main_content%} {%endblock%}

        <div class="footer">
            <p>Made in 2022</p>
            <p>Copyright &copy;kamana</p>
        </div>
    </body>
</html>

user/templates/user/signin.html
<h1>Login</h1>

<form method="Post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Signin"/>
</form>

user/templates/user/update.html
<a href="{% url 'user:blogs' %}"> Back </a>
<form method="POST">
{%csrf_token%}
{{ form_as.p }}
<input type="submit" value="Edit"/>
</form>